# Generated by Django 6.0.4 on 2026-06-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=255, verbose_name='Пошуковий запит')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('name', models.CharField(db_index=True, max_length=500, verbose_name='Назва препарату')),
                ('nameNormalized', models.CharField(db_index=True, max_length=500)),
                ('product_id', models.IntegerField()),
                ('pharmacy', models.CharField(db_index=True, max_length=100, verbose_name='Аптека')),
                ('price', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна')),
                ('alias', models.URLField(max_length=1000, verbose_name='Посилання')),
                ('brand', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Бренд')),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Картинка')),
                ('stock_status', models.CharField(choices=[('in_stock', 'Є'), ('out_of_stock', 'Немає'), ('unknown', 'Невідомо')], db_index=True, default='unknown', max_length=20, verbose_name='Наявність')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Результат пошуку',
                'verbose_name_plural': 'Результати пошуку',
                'ordering': ['price'],
                'indexes': [models.Index(fields=['query'], name='home_search_query_cc9589_idx'), models.Index(fields=['pharmacy'], name='home_search_pharmac_779312_idx'), models.Index(fields=['price'], name='home_search_price_bb56b9_idx'), models.Index(fields=['brand'], name='home_search_brand_2d82f0_idx'), models.Index(fields=['stock_status'], name='home_search_stock_s_a808a9_idx')],
            },
        ),
    ]
