# Generated by Django 6.0.4 on 2026-06-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Картинка'),
        ),
    ]
